import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import './globals.css'
import Bars from '@/components/Bars'

const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">

      <body className={`${inter.className} w-full h-screen  `}>
        <Bars/>
      {children}
      </body>
      <script src="https://accounts.google.com/gsi/client" async defer></script>
    </html>
  )
}
